'use client';

import React, { useContext, useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber/webgpu';
import * as THREE from 'three/webgpu';
import { float, vec3 } from 'three/tsl';

import { BalloonOpacityContext } from '../CrystalBalloonIndicator';

/**
 * Builds a 4-pointed star (rhombus with sharper spikes) centered on origin.
 * 8 vertices alternate between `outerRadius` (spike tip) and `innerRadius`
 * (valley), starting at +Y.
 */
function createFourPointStarGeometry(
  outerRadius: number,
  innerRadius: number,
): THREE.ShapeGeometry {
  const shape = new THREE.Shape();
  const pointCount = 8;
  const pts: Array<[number, number]> = [];
  for (let i = 0; i < pointCount; i++) {
    const angle = (i / pointCount) * Math.PI * 2 - Math.PI / 2;
    const r = i % 2 === 0 ? outerRadius : innerRadius;
    pts.push([Math.cos(angle) * r, Math.sin(angle) * r]);
  }
  shape.moveTo(pts[0][0], pts[0][1]);
  for (let i = 1; i < pts.length; i++) {
    shape.lineTo(pts[i][0], pts[i][1]);
  }
  shape.lineTo(pts[0][0], pts[0][1]);
  return new THREE.ShapeGeometry(shape);
}

const STAR_OUTER_RADIUS = 0.15;
const STAR_INNER_RADIUS = 0.055;
const STAR_GEOMETRY = createFourPointStarGeometry(
  STAR_OUTER_RADIUS,
  STAR_INNER_RADIUS,
);
const STAR_CENTER_GEOMETRY = new THREE.CircleGeometry(0.026, 18);

const SPIN_PERIOD_S = 4;
const PULSE_PERIOD_S = 1.4;
const PULSE_AMPLITUDE = 0.08;

const TRIAL_COLOR_RGB = { r: 1.0, g: 0.86, b: 0.42 } as const;

const MIN_DELTA_CLAMP_S = 1 / 20;

/**
 * Trial-ritual glyph — a 4-pointed spinning star with a pulsing core, rendered
 * inside a {@link CrystalBalloonIndicator} to mark a crystal whose Crystal Trial
 * questions are being pregenerated by the LLM pipeline.
 *
 * Requires {@link BalloonOpacityContext} so the star fades in lockstep with
 * the surrounding balloon. Throws when rendered outside a balloon, per
 * CLAUDE.md "Explicit Failure".
 */
export const TrialGlyph: React.FC = () => {
  const opacityUniform = useContext(BalloonOpacityContext);
  if (!opacityUniform) {
    throw new Error(
      'TrialGlyph must be rendered inside a <CrystalBalloonIndicator> (BalloonOpacityContext is missing).',
    );
  }

  const starRef = useRef<THREE.Group>(null);
  const elapsedRef = useRef(0);

  const material = useMemo(() => {
    const mat = new THREE.MeshBasicNodeMaterial({
      transparent: true,
      depthWrite: false,
      side: THREE.DoubleSide,
      toneMapped: false,
    });
    mat.colorNode = vec3(
      float(TRIAL_COLOR_RGB.r),
      float(TRIAL_COLOR_RGB.g),
      float(TRIAL_COLOR_RGB.b),
    );
    mat.opacityNode = opacityUniform;
    return mat;
  }, [opacityUniform]);

  useFrame((_state, delta) => {
    const dt = Math.min(delta, MIN_DELTA_CLAMP_S);
    elapsedRef.current += dt;

    const star = starRef.current;
    if (star) {
      star.rotation.z -= (dt * Math.PI * 2) / SPIN_PERIOD_S;
      const pulse =
        1 +
        PULSE_AMPLITUDE *
          Math.sin((elapsedRef.current * Math.PI * 2) / PULSE_PERIOD_S);
      star.scale.setScalar(pulse);
    }
  });

  return (
    <group ref={starRef}>
      <mesh geometry={STAR_GEOMETRY} material={material} />
      <mesh geometry={STAR_CENTER_GEOMETRY} material={material} />
    </group>
  );
};

export default TrialGlyph;
