'use client';

import React from 'react';

import {
  CrystalBalloonIndicator,
  ClockGlyph,
  type CrystalBalloonIndicatorColorRgb,
} from './crystalBalloon';

interface CrystalGeneratingIndicatorProps {
  position: [number, number, number];
  /** When false the indicator fades out smoothly; true fades in (or stays visible). */
  active: boolean;
  /** Called once when the fade-out reaches zero opacity. */
  onFadeOutComplete?: () => void;
}

const BORDER_COLOR: Readonly<CrystalBalloonIndicatorColorRgb> = {
  r: 0.45,
  g: 0.9,
  b: 1.0,
};
const FILL_COLOR: Readonly<CrystalBalloonIndicatorColorRgb> = {
  r: 0.04,
  g: 0.08,
  b: 0.13,
};

/**
 * Balloon-style indicator rendered above a crystal while its study content
 * (theory + card deck) is being generated by the LLM pipeline.
 *
 * Thin wrapper around {@link CrystalBalloonIndicator} that supplies the
 * content-generation glyph (a spinning analog clock) and the cool-cyan tint
 * conventionally used for content-generation surfaces across the app.
 */
export const CrystalGeneratingIndicator: React.FC<
  CrystalGeneratingIndicatorProps
> = ({ position, active, onFadeOutComplete }) => (
  <CrystalBalloonIndicator
    position={position}
    active={active}
    onFadeOutComplete={onFadeOutComplete}
    borderColor={BORDER_COLOR}
    fillColor={FILL_COLOR}
  >
    <ClockGlyph />
  </CrystalBalloonIndicator>
);

export default CrystalGeneratingIndicator;
