/**
 * Build-time generator for `src/graphics/labels/generated/topicIconNodes.ts`.
 *
 * Pipeline:
 *   TOPIC_ICON_NAMES allowlist
 *     -> lucide raw icon nodes (this script)
 *     -> src/graphics/labels/generated/topicIconNodes.ts (committed)
 *     -> drawTopicIcon (runtime)
 *
 * The runtime never imports `lucide` or `lucide-react`. Adding or removing
 * a topic icon requires:
 *   1. Updating TOPIC_ICON_NAMES in topicIconAllowlist.ts.
 *   2. Updating the TopicIconName literal union in src/types/core.ts.
 *   3. Re-running `pnpm generate:topic-icons` and committing the resulting
 *      `topicIconNodes.ts` change.
 *
 * CI guards drift via `pnpm check:topic-icons`, which regenerates and diffs.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { icons } from 'lucide';
import { TOPIC_ICON_NAMES } from '../src/features/subjectGeneration/graph/topicIcons/topicIconAllowlist';

const SUPPORTED_TAGS = new Set([
  'path',
  'line',
  'circle',
  'rect',
  'polyline',
  'polygon',
  'ellipse',
]);

const OUTPUT_PATH = 'src/graphics/labels/generated/topicIconNodes.ts';

function toPascalCase(iconName: string): string {
  return iconName
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

type RawIconNode = ReadonlyArray<readonly [string, Record<string, unknown>]>;

const generatedEntries = TOPIC_ICON_NAMES.map((iconName) => {
  const lucideExportName = toPascalCase(iconName);
  const iconNode = (icons as Record<string, RawIconNode | undefined>)[lucideExportName];

  if (!iconNode) {
    throw new Error(
      `Missing Lucide icon export for "${iconName}" as "${lucideExportName}".`,
    );
  }

  for (const primitive of iconNode) {
    const [tag] = primitive;
    if (!SUPPORTED_TAGS.has(tag)) {
      throw new Error(
        `Unsupported Lucide primitive "${tag}" in icon "${iconName}". Update SUPPORTED_TAGS and drawTopicIcon together.`,
      );
    }
  }

  return [iconName, iconNode] as const;
});

const generatedObject = Object.fromEntries(generatedEntries);

const output = `// Generated by scripts/generate-topic-icon-nodes.ts.
// Do not edit manually. Run \`pnpm generate:topic-icons\` to refresh.

import type { TopicIconName } from '@/types/core';

/**
 * Tagged-tuple union over the 7 supported SVG primitive tags. Mirrors the
 * shape that \`lucide\` exposes via \`icons.<PascalCaseIconName>\`. \`fill\` is
 * permitted because some Lucide icons (e.g., palette) ship monochrome filled
 * accents alongside their stroke outlines.
 */
export type GeneratedTopicIconPrimitive =
  | readonly ['path', { readonly d: string; readonly fill?: string; readonly key?: string }]
  | readonly [
      'line',
      {
        readonly x1: string | number;
        readonly y1: string | number;
        readonly x2: string | number;
        readonly y2: string | number;
        readonly fill?: string;
        readonly key?: string;
      },
    ]
  | readonly [
      'circle',
      {
        readonly cx: string | number;
        readonly cy: string | number;
        readonly r: string | number;
        readonly fill?: string;
        readonly key?: string;
      },
    ]
  | readonly [
      'rect',
      {
        readonly x: string | number;
        readonly y: string | number;
        readonly width: string | number;
        readonly height: string | number;
        readonly rx?: string | number;
        readonly ry?: string | number;
        readonly fill?: string;
        readonly key?: string;
      },
    ]
  | readonly ['polyline', { readonly points: string; readonly fill?: string; readonly key?: string }]
  | readonly ['polygon', { readonly points: string; readonly fill?: string; readonly key?: string }]
  | readonly [
      'ellipse',
      {
        readonly cx: string | number;
        readonly cy: string | number;
        readonly rx: string | number;
        readonly ry: string | number;
        readonly fill?: string;
        readonly key?: string;
      },
    ];

export const GENERATED_TOPIC_ICON_NODES = ${JSON.stringify(generatedObject, null, 2)} as const satisfies Record<
  TopicIconName,
  readonly GeneratedTopicIconPrimitive[]
>;
`;

await mkdir(dirname(OUTPUT_PATH), { recursive: true });
await writeFile(OUTPUT_PATH, output);

console.log(`Wrote ${TOPIC_ICON_NAMES.length} topic icons to ${OUTPUT_PATH}.`);
