/**
 * Build-time generator for `src/graphics/labels/generated/mentorIconNodes.ts`.
 *
 * Pipeline:
 *   MENTOR_ICON_NAMES allowlist
 *     -> lucide raw icon nodes (this script) + hand-authored philosopher-stone
 *     -> src/graphics/labels/generated/mentorIconNodes.ts (committed)
 *     -> drawMentorIcon (runtime)
 *
 * The runtime never imports `lucide` or `lucide-react`. Adding or removing
 * a mentor icon requires:
 *   1. Updating MENTOR_ICON_NAMES in src/features/mentor/mentorIconAllowlist.ts.
 *   2. Updating the MentorIconName literal union in src/types/core.ts.
 *   3. Re-running `pnpm generate:mentor-icons` and committing the resulting
 *      `mentorIconNodes.ts` change.
 *
 * The non-Lucide `philosopher-stone` glyph is hand-authored here (NOT in the
 * emitted file's footer) so the emitted file stays a pure data table. The
 * proportions match OQ1 (corrected): outer circle r=11, inscribed triangle,
 * inner square side 8.7, inner circle r=3.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { icons } from 'lucide';
import { MENTOR_ICON_NAMES } from '../src/features/mentor/mentorIconAllowlist';

const SUPPORTED_TAGS = new Set([
  'path',
  'line',
  'circle',
  'rect',
  'polyline',
  'polygon',
  'ellipse',
]);

const OUTPUT_PATH = 'src/graphics/labels/generated/mentorIconNodes.ts';

function toPascalCase(iconName: string): string {
  return iconName
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

type RawIconNode = ReadonlyArray<readonly [string, Record<string, unknown>]>;

/**
 * Hand-authored vector primitives for the custom `philosopher-stone` glyph.
 *
 * Layout (24 viewBox), OQ1-corrected so the inscribed square fits inside the
 * inscribed triangle:
 *   - Outer circle  : cx=12 cy=12 r=11
 *   - Triangle      : 12,2 21.5,18 2.5,18
 *   - Square        : x=7.65 y=9.3 width=8.7 height=8.7
 *   - Inner circle  : cx=12 cy=13.65 r=3
 *
 * The rasterizer must add padding >= half the stroke width so the outer
 * circle stroke does not clip against the canvas edge.
 */
const PHILOSOPHER_STONE_NODES: RawIconNode = [
  ['circle', { cx: '12', cy: '12', r: '11' }],
  ['polygon', { points: '12,2 21.5,18 2.5,18' }],
  ['rect', { x: '7.65', y: '9.3', width: '8.7', height: '8.7' }],
  ['circle', { cx: '12', cy: '13.65', r: '3' }],
] as const;

const generatedEntries = MENTOR_ICON_NAMES.map((iconName) => {
  if (iconName === 'philosopher-stone') {
    return [iconName, PHILOSOPHER_STONE_NODES] as const;
  }

  const lucideExportName = toPascalCase(iconName);
  const iconNode = (icons as Record<string, RawIconNode | undefined>)[lucideExportName];

  if (!iconNode) {
    throw new Error(
      `Missing Lucide icon export for "${iconName}" as "${lucideExportName}".`,
    );
  }

  for (const primitive of iconNode) {
    const [tag] = primitive;
    if (!SUPPORTED_TAGS.has(tag)) {
      throw new Error(
        `Unsupported Lucide primitive "${tag}" in icon "${iconName}". Update SUPPORTED_TAGS and drawIconPrimitives together.`,
      );
    }
  }

  return [iconName, iconNode] as const;
});

const generatedObject = Object.fromEntries(generatedEntries);

const output = `// Generated by scripts/generate-mentor-icon-nodes.ts.
// Do not edit manually. Run \`pnpm generate:mentor-icons\` to refresh.

import type { MentorIconName } from '@/types/core';
import type { GeneratedTopicIconPrimitive } from './topicIconNodes';

/**
 * Mentor-icon vector primitives reuse the same tagged-tuple union as topic
 * icons (\`GeneratedTopicIconPrimitive\`), since both surfaces share the
 * \`drawIconPrimitives\` rasterizer. The mentor and topic vocabularies stay
 * disjoint at the \`Record<...>\` key level.
 */
export type GeneratedMentorIconPrimitive = GeneratedTopicIconPrimitive;

export const GENERATED_MENTOR_ICON_NODES = ${JSON.stringify(generatedObject, null, 2)} as const satisfies Record<
  MentorIconName,
  readonly GeneratedMentorIconPrimitive[]
>;
`;

await mkdir(dirname(OUTPUT_PATH), { recursive: true });
await writeFile(OUTPUT_PATH, output);

console.log(`Wrote ${MENTOR_ICON_NAMES.length} mentor icons to ${OUTPUT_PATH}.`);
